-- Pinoy Pocket Budget: accounts, profiles, recurring schedules, and transaction links.
-- Additive and idempotent. Existing transactions, loans, cards, and debt records are preserved.

begin;

create table if not exists public.budget_accounts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  account_type text not null check (account_type in ('bank_wallet', 'cash_on_hand')),
  name text not null check (char_length(btrim(name)) between 1 and 80),
  provider text not null default '' check (char_length(provider) <= 80),
  available_balance numeric(14,2) not null default 0 check (available_balance >= 0),
  protected_balance numeric(14,2) not null default 0 check (protected_balance >= 0),
  savings_balance numeric(14,2) not null default 0 check (savings_balance >= 0),
  color_key text not null default 'emerald' check (char_length(color_key) <= 30),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint budget_accounts_reserves_within_balance check (protected_balance + savings_balance <= available_balance)
);

create index if not exists budget_accounts_user_id_idx on public.budget_accounts(user_id);

create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  first_name text not null default '' check (char_length(first_name) <= 80),
  surname text not null default '' check (char_length(surname) <= 80),
  mobile_number text not null default '' check (char_length(mobile_number) <= 30),
  house_unit text not null default '' check (char_length(house_unit) <= 120),
  street_barangay text not null default '' check (char_length(street_barangay) <= 160),
  city_municipality text not null default '' check (char_length(city_municipality) <= 120),
  province text not null default '' check (char_length(province) <= 120),
  country text not null default '' check (char_length(country) <= 80),
  zip_code text not null default '' check (char_length(zip_code) <= 20),
  avatar_path text,
  tutorial_completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.recurring_schedules (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  source_account_id bigint references public.budget_accounts(id) on delete restrict,
  credit_card_id bigint references public.credit_cards(id) on delete restrict,
  category text not null,
  description text not null default '',
  amount numeric(14,2) not null check (amount > 0),
  frequency text not null check (frequency in ('monthly', 'quarterly', 'annually', 'installment')),
  start_date date not null,
  end_date date,
  installment_count integer check (installment_count between 1 and 60),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint recurring_schedule_source check ((source_account_id is not null)::integer + (credit_card_id is not null)::integer = 1),
  constraint recurring_schedule_dates check (end_date is null or end_date >= start_date),
  constraint installment_count_required check ((frequency = 'installment' and installment_count is not null) or (frequency <> 'installment' and installment_count is null))
);

create index if not exists recurring_schedules_user_date_idx on public.recurring_schedules(user_id, start_date) where active;

alter table public.transactions add column if not exists account_id bigint references public.budget_accounts(id) on delete restrict;
alter table public.transactions add column if not exists credit_card_id bigint references public.credit_cards(id) on delete restrict;
alter table public.transactions add column if not exists savings_amount numeric(14,2) not null default 0 check (savings_amount >= 0);
alter table public.transactions add column if not exists due_date date;
alter table public.transactions add column if not exists recurring_schedule_id bigint references public.recurring_schedules(id) on delete set null;

alter table public.budget_accounts enable row level security;
alter table public.user_profiles enable row level security;
alter table public.recurring_schedules enable row level security;

drop policy if exists "Users select own budget accounts" on public.budget_accounts;
create policy "Users select own budget accounts" on public.budget_accounts for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "Users insert own budget accounts" on public.budget_accounts;
create policy "Users insert own budget accounts" on public.budget_accounts for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "Users update own budget accounts" on public.budget_accounts;
create policy "Users update own budget accounts" on public.budget_accounts for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users delete own budget accounts" on public.budget_accounts;
create policy "Users delete own budget accounts" on public.budget_accounts for delete to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "Users select own profile" on public.user_profiles;
create policy "Users select own profile" on public.user_profiles for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "Users insert own profile" on public.user_profiles;
create policy "Users insert own profile" on public.user_profiles for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "Users update own profile" on public.user_profiles;
create policy "Users update own profile" on public.user_profiles for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users delete own profile" on public.user_profiles;
create policy "Users delete own profile" on public.user_profiles for delete to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "Users select own recurring schedules" on public.recurring_schedules;
create policy "Users select own recurring schedules" on public.recurring_schedules for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "Users insert own recurring schedules" on public.recurring_schedules;
create policy "Users insert own recurring schedules" on public.recurring_schedules for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "Users update own recurring schedules" on public.recurring_schedules;
create policy "Users update own recurring schedules" on public.recurring_schedules for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users delete own recurring schedules" on public.recurring_schedules;
create policy "Users delete own recurring schedules" on public.recurring_schedules for delete to authenticated using ((select auth.uid()) = user_id);

grant select, insert, update, delete on public.budget_accounts, public.user_profiles, public.recurring_schedules to authenticated;
grant usage, select on sequence public.budget_accounts_id_seq, public.recurring_schedules_id_seq to authenticated;
grant select, insert, update on public.transactions to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('profile-photos', 'profile-photos', false, 5242880, array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Users read own profile photos" on storage.objects;
create policy "Users read own profile photos" on storage.objects for select to authenticated
using (bucket_id = 'profile-photos' and (storage.foldername(name))[1] = (select auth.uid())::text);
drop policy if exists "Users upload own profile photos" on storage.objects;
create policy "Users upload own profile photos" on storage.objects for insert to authenticated
with check (bucket_id = 'profile-photos' and (storage.foldername(name))[1] = (select auth.uid())::text);
drop policy if exists "Users update own profile photos" on storage.objects;
create policy "Users update own profile photos" on storage.objects for update to authenticated
using (bucket_id = 'profile-photos' and (storage.foldername(name))[1] = (select auth.uid())::text)
with check (bucket_id = 'profile-photos' and (storage.foldername(name))[1] = (select auth.uid())::text);
drop policy if exists "Users delete own profile photos" on storage.objects;
create policy "Users delete own profile photos" on storage.objects for delete to authenticated
using (bucket_id = 'profile-photos' and (storage.foldername(name))[1] = (select auth.uid())::text);

commit;
