type PublicPage = 'help' | 'privacy' | 'terms'
const support = 'support@pinoypocketbudget.app'

const helpTopics = [
  ['Getting started', 'Set up the app in the right order so balances and reports begin accurately.', ['Create your account, confirm your email, and sign in.', 'Add every bank, digital wallet, and Cash on Hand account that currently holds available money.', 'Enter each account’s current balance as its opening balance. Opening balances are not treated as income.', 'Add existing loans and credit cards before recording transactions connected to them.', 'Record new income and expenses from their actual transaction dates.']],
  ['Navigating the app', 'Understand the main areas and the Add button.', ['Overview summarizes available funds, spending, debts, and recent activity.', 'Activity contains searchable transaction history and expense details.', 'Debts contains your loans and credit cards.', 'Use Add to record income or an expense from the main screen.']],
  ['Accounts and Cash on Hand', 'Track money held in banks, wallets, and physical cash.', ['Add every account that currently holds available money.', 'Use the current balance—not lifetime deposits—as its opening balance.', 'Balance corrections should remain visible as adjustments rather than income or expenses.']],
  ['Recording income', 'Add income using its actual destination and transaction date.', ['Select Add, then choose Income.', 'Enter the amount, source or description, category, and date.', 'Review the information and save the income.']],
  ['Recording expenses', 'Record each expense under the category and date that accurately describe it.', ['Select Add, then choose Expense.', 'Enter the amount, description, category, and transaction date.', 'Credit-card purchases should be linked to the correct card so utilization stays accurate.', 'Review the information and save the expense.']],
  ['Recurring expenses and subscriptions', 'Plan monthly, quarterly, or annual obligations without losing their history.', ['Keep the start date and recurrence interval accurate.', 'Editing a schedule should affect future occurrences, not rewrite existing transactions.', 'Installment schedules should stop after the final installment.']],
  ['Credit cards', 'Monitor balances, available credit, minimum payments, statement dates, and due dates.', ['Add the card name, issuer, credit limit, balances, minimum payment, statement day, and due day.', 'Record purchases as expenses against the correct card.', 'Use Pay or Adjust to reconcile the current balance.']],
  ['Loans', 'Track remaining balances, monthly repayments, and upcoming due dates.', ['Enter the loan name, lender, original amount, current balance, monthly payment, and next due date.', 'Use Pay for repayments and Adjust for fees, interest, or corrections.', 'Review overdue and upcoming installments before recording a duplicate payment.']],
  ['Paying loans and credit cards', 'Record the cash movement and debt reduction together.', ['Open the related loan or card and choose Pay.', 'Enter the amount and payment date, then confirm.', 'Use partial payments carefully because the remaining balance stays due.', 'Debt repayments reduce debt and available money but should not be double-counted as ordinary spending.']],
  ['Projected Disposable Income', 'Estimate what remains after savings reserves and upcoming obligations.', ['Begin with currently available funds.', 'Deduct upcoming loan payments, card dues, and recurring expenses once.', 'A negative result means scheduled obligations exceed currently available disposable funds.']],
  ['Activity and transaction history', 'Review recorded money movements from newest to oldest.', ['Search by description or category.', 'Use date filters to review a specific period.', 'Opening balances and balance adjustments should remain visible without counting as income or expenses.']],
  ['Due-date alerts', 'Review upcoming and overdue obligations and manage email delivery.', ['Open Account Settings.', 'Enable or pause due-report emails.', 'Reports cover upcoming and overdue loan and credit-card payments.', 'Open the related debt to record or confirm payment.']],
  ['Editing and deleting safely', 'Understand how corrections affect linked balances.', ['Review a proposed correction before saving it.', 'Linked purchases and payments must reconcile their associated debt balance.', 'Avoid deleting records when doing so would disconnect related payments or allocations.']],
  ['Profile, security, and account deletion', 'Manage your account and permanently remove your data when needed.', ['Select the settings icon to open Account Settings.', 'Open policies, visit the Help Center, contact support, or sign out.', 'To permanently delete the account, open Danger Zone and type DELETE.', 'Deletion permanently removes sign-in access and associated app records and cannot be undone.']],
  ['Troubleshooting', 'Resolve common entry, balance, and sign-in problems.', ['If an entry cannot be saved, confirm the amount, category, date, and available balance.', 'If a card balance looks incorrect, check purchases, payments, and adjustments before repeating an entry.', 'Check spam if an account or password-recovery email does not arrive.', 'For a reconciliation warning, do not repeat the transaction. Contact support with the date, amount, and account name.']],
] as const

const terms = [
  ['1. Eligibility and accounts', 'You must be at least 18 years old and legally capable of entering into an agreement. You must provide accurate account information, keep your password confidential, and promptly notify us if you suspect unauthorized access. You are responsible for activity conducted through your account.'],
  ['2. What the service provides', 'Pinoy Pocket Budget provides tools for manually recording and organizing personal income, expenses, loans, and credit-card balances. The service does not hold money, initiate bank transactions, extend credit, collect debt, process card payments, or connect directly to your financial accounts. Calculations, summaries, and reminders are informational tools only and are not financial, investment, tax, accounting, or legal advice.'],
  ['3. Beta service', 'The service is offered for public beta testing. Features may be incomplete, contain errors, change, or become temporarily unavailable. Use sample information where possible during testing and maintain your own backup of important records.'],
  ['4. Acceptable use', 'You must not attempt to access another person’s account or records, interfere with security, disrupt the service, upload malicious material, automate abusive requests, violate another person’s rights, or use the service for unlawful, fraudulent, or harmful activity.'],
  ['5. Your content', 'You retain ownership of the information you enter. You grant us limited permission to host, process, copy, transmit, and display it only as needed to operate, secure, support, and improve the service and comply with law.'],
  ['6. Plans and payments', 'The app may display proposed subscription plans, but live payment processing is not currently enabled. Selecting a displayed plan does not start a subscription or create a charge.'],
  ['7. Availability and changes', 'We may add, remove, suspend, or change features and perform maintenance without prior notice when reasonably necessary to operate or protect the service.'],
  ['8. Disclaimers', 'To the extent permitted by law, the beta service is provided as is and as available. We do not guarantee uninterrupted availability or the accuracy of information entered by users or results based on that information.'],
  ['9. Ending your use', `You may stop using the service at any time. Signed-in users can permanently delete their account and associated data through Account Settings. If self-service deletion is unavailable, email ${support} from the address associated with your account.`],
  ['10. Governing law and contact', `These Terms are governed by the laws of the Republic of the Philippines. Questions may be sent to ${support}. Mandatory consumer rights remain unaffected.`],
] as const

const privacy = [
  ['1. Who is responsible for your data', `Pinoy Pocket Budget acts as the personal information controller for information collected through this service. Privacy requests may be sent to ${support}.`],
  ['2. Information we collect', 'We process your email address, optional profile information, account identifier and timestamps; the income, expense, loan, and credit-card information you enter; essential authentication, error, and security logs; and messages you send to support.'],
  ['3. Information you should not enter', 'Do not enter full card numbers, security codes, bank passwords, government identification numbers, or other information the app does not request. Pinoy Pocket Budget does not connect directly to your bank or card account.'],
  ['4. How and why we use information', 'We use information to create and secure your account, provide budgeting features, store and synchronize entries, send account and due-date emails, respond to support requests, prevent abuse, diagnose errors, and comply with applicable law.'],
  ['5. Service providers and transfers', 'Supabase provides authentication and database services, while email, hosting, and domain providers help operate the app. Their systems may process information outside the Philippines. We do not sell personal information or share personal budget entries with advertisers.'],
  ['6. Storage, security, and retention', 'Authentication and database access controls are designed to separate each user’s records. No online service can guarantee absolute security. We retain information while your account is active and as reasonably necessary for support, security, disputes, or legal obligations.'],
  ['7. Cookies and local storage', 'The app and its providers may use cookies or browser storage needed to keep you signed in, maintain security, remember essential settings, and operate the service. We do not currently use this information for targeted advertising.'],
  ['8. Your privacy rights', `Subject to applicable law, you may request access, correction, objection, portability, erasure, or blocking. Use Account Settings or contact ${support}. You may also contact the Philippine National Privacy Commission.`],
  ['9. Children and policy changes', 'The service is intended for people at least 18 years old. We do not knowingly collect information from children. Updated policies will be posted here with a revised effective date.'],
] as const

export function PublicPages({ page }: { page: PublicPage }) {
  if (page === 'help') return <main className="public-page help-page"><nav><a href="/" className="wordmark"><span>₱</span> Pinoy Pocket Budget</a><a href="/">← Back to app</a></nav><article><span className="eyebrow">KNOWLEDGE BASE</span><h1>How can we help?</h1><p className="lead">Step-by-step guidance for navigating and using Pinoy Pocket Budget accurately.</p><div className="topic-count">15 topics</div><div className="help-grid">{helpTopics.map(([title, summary, steps], index) => <section id={`topic-${index + 1}`} key={title}><b>{String(index + 1).padStart(2, '0')}</b><h2>{title}</h2><p>{summary}</p><ul>{steps.map(step => <li key={step}>{step}</li>)}</ul></section>)}</div><aside><span className="eyebrow">NEED MORE HELP?</span><h2>Contact Pinoy Pocket Budget support</h2><p>Include the transaction date, amount, and account name when reporting a balance issue. Never send your password.</p><a href={`mailto:${support}`}>{support}</a></aside></article></main>
  const isTerms = page === 'terms'
  const sections = isTerms ? terms : privacy
  return <main className="public-page"><nav><a href="/" className="wordmark"><span>₱</span> Pinoy Pocket Budget</a><a href="/">Back to app</a></nav><article><span className="eyebrow">{isTerms ? 'PLEASE READ BEFORE USING' : 'YOUR DATA, EXPLAINED'}</span><h1>{isTerms ? 'Terms of Service' : 'Privacy Policy'}</h1><p className="updated">Effective and last updated: August 22, 2026</p><p className="lead">{isTerms ? 'These Terms govern your use of Pinoy Pocket Budget. By creating an account or using the service, you agree to these Terms and acknowledge the Privacy Policy.' : 'Pinoy Pocket Budget is a personal budgeting and debt-tracking service operated by its individual owner in the Philippines. This policy explains what information we process, why we need it, and the choices available to you.'}</p>{sections.map(([title, body]) => <section key={title}><h2>{title}</h2><p>{body}</p></section>)}<footer><a href={isTerms ? '/privacy' : '/terms'}>{isTerms ? 'Privacy Policy' : 'Terms of Service'}</a><a href={`mailto:${support}`}>Contact support</a><a href="/">Return to app</a></footer></article></main>
}