create table if not exists public.user_notification_settings(
 user_id uuid primary key references auth.users(id) on delete cascade,
 due_reports_enabled boolean not null default true,
 updated_at timestamptz not null default now()
);

create table if not exists public.due_report_deliveries(
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 debt_type text not null check(debt_type in('loan','credit_card')),
 debt_id bigint not null,
 due_date date not null,
 report_type text not null check(report_type in('upcoming_15_days','overdue_3_days')),
 resend_email_id text,
 sent_at timestamptz not null default now(),
 unique(user_id,debt_type,debt_id,due_date,report_type)
);

create index if not exists due_report_deliveries_user_id_idx on public.due_report_deliveries(user_id);

alter table public.user_notification_settings enable row level security;
alter table public.due_report_deliveries enable row level security;

drop policy if exists "Users manage own notification settings" on public.user_notification_settings;
create policy "Users manage own notification settings"
 on public.user_notification_settings for all to authenticated
 using((select auth.uid())=user_id)
 with check((select auth.uid())=user_id);

drop policy if exists "Users view own due report deliveries" on public.due_report_deliveries;
create policy "Users view own due report deliveries"
 on public.due_report_deliveries for select to authenticated
 using((select auth.uid())=user_id);

create or replace view public.due_report_items with(security_invoker=true) as
select l.id as debt_id,l.user_id,l.name,'loan'::text as debt_type,l.balance as amount_due,l.due as due_date
from public.loans l
where l.balance>0
union all
select c.id as debt_id,c.user_id,c.name,'credit_card'::text as debt_type,c.current_balance as amount_due,
 make_date(extract(year from m.month_start)::int,extract(month from m.month_start)::int,
  least(c.due_day,extract(day from (m.month_start+interval '1 month'-interval '1 day'))::int)) as due_date
from public.credit_cards c
cross join lateral(
 select (date_trunc('month',current_date)+(n||' month')::interval)::date as month_start
 from generate_series(0,1) as n
) m
where c.current_balance>0;

revoke all on public.due_report_items from anon,authenticated;
grant select on public.due_report_items to service_role;
grant select,insert,update,delete on public.user_notification_settings to authenticated;
grant select on public.due_report_deliveries to authenticated;

-- After deploying send-due-reports, store DUE_REPORT_CRON_SECRET in Vault and
-- schedule the function from Supabase Cron at 00:15 UTC daily.
