-- Pinoy Pocket Budget
-- First tracked migration: structured debt adjustments and payments
-- Review only. Do not apply until the frontend and Edge Function changes are ready.

begin;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.debt_adjustments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  debt_type text not null check (debt_type in ('loan', 'credit_card')),
  loan_id bigint references public.loans(id) on delete cascade,
  credit_card_id bigint references public.credit_cards(id) on delete cascade,
  adjustment_type text not null check (
    adjustment_type in (
      'finance_charge',
      'late_fee',
      'over_limit_fee',
      'annual_fee',
      'additional_interest',
      'collection_fee',
      'restructuring_fee',
      'other_charge',
      'credit',
      'reversal'
    )
  ),
  amount numeric(14,2) not null check (amount > 0),
  signed_amount numeric(14,2) generated always as (
    case when adjustment_type in ('credit', 'reversal') then -amount else amount end
  ) stored,
  effective_date date not null default current_date,
  due_date date not null,
  description text not null default '',
  source_transaction_id bigint references public.transactions(id) on delete set null,
  reverses_adjustment_id bigint references public.debt_adjustments(id) on delete restrict,
  status text not null default 'posted' check (status in ('posted', 'void')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint debt_adjustments_target_check check (
    (debt_type = 'loan' and loan_id is not null and credit_card_id is null)
    or
    (debt_type = 'credit_card' and credit_card_id is not null and loan_id is null)
  ),
  constraint debt_adjustments_reversal_check check (
    (adjustment_type = 'reversal' and reverses_adjustment_id is not null)
    or
    (adjustment_type <> 'reversal' and reverses_adjustment_id is null)
  )
);

create table public.debt_payments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  debt_type text not null check (debt_type in ('loan', 'credit_card')),
  loan_id bigint references public.loans(id) on delete cascade,
  credit_card_id bigint references public.credit_cards(id) on delete cascade,
  amount numeric(14,2) not null check (amount > 0),
  payment_date date not null default current_date,
  source_account_key text,
  source_transaction_id bigint references public.transactions(id) on delete set null,
  legacy_due_key text,
  status text not null default 'posted' check (status in ('posted', 'void')),
  note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint debt_payments_target_check check (
    (debt_type = 'loan' and loan_id is not null and credit_card_id is null)
    or
    (debt_type = 'credit_card' and credit_card_id is not null and loan_id is null)
  )
);

create table public.payment_allocations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  payment_id bigint not null references public.debt_payments(id) on delete cascade,
  adjustment_id bigint references public.debt_adjustments(id) on delete restrict,
  component text not null check (
    component in (
      'principal',
      'interest',
      'finance_charge',
      'late_fee',
      'penalty',
      'fee',
      'other'
    )
  ),
  amount numeric(14,2) not null check (amount > 0),
  created_at timestamptz not null default now()
);

create or replace function public.validate_debt_accounting_row()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  owner_id uuid;
  reversed_row public.debt_adjustments%rowtype;
begin
  if new.source_transaction_id is not null then
    perform pg_advisory_xact_lock(
      hashtextextended('ppb-source-transaction:' || new.source_transaction_id::text, 0)
    );
  end if;

  if new.debt_type = 'loan' then
    select user_id into owner_id from public.loans where id = new.loan_id;
  else
    select user_id into owner_id from public.credit_cards where id = new.credit_card_id;
  end if;

  if owner_id is null or owner_id <> new.user_id then
    raise exception 'Debt target does not belong to the user';
  end if;

  if new.source_transaction_id is not null then
    select user_id into owner_id
    from public.transactions
    where id = new.source_transaction_id;

    if owner_id is null or owner_id <> new.user_id then
      raise exception 'Source transaction does not belong to the user';
    end if;

    if tg_table_name = 'debt_adjustments'
       and exists (
         select 1 from public.debt_payments
         where user_id = new.user_id
           and source_transaction_id = new.source_transaction_id
           and status = 'posted'
       ) then
      raise exception 'Source transaction is already linked to a payment';
    end if;

    if tg_table_name = 'debt_payments'
       and exists (
         select 1 from public.debt_adjustments
         where user_id = new.user_id
           and source_transaction_id = new.source_transaction_id
           and status = 'posted'
       ) then
      raise exception 'Source transaction is already linked to an adjustment';
    end if;
  end if;

  if tg_table_name = 'debt_adjustments' and new.reverses_adjustment_id is not null then
    perform pg_advisory_xact_lock(
      hashtextextended('ppb-adjustment-reversal:' || new.reverses_adjustment_id::text, 0)
    );

    select * into reversed_row
    from public.debt_adjustments
    where id = new.reverses_adjustment_id;

    if reversed_row.id is null
       or reversed_row.user_id <> new.user_id
       or reversed_row.debt_type <> new.debt_type
       or reversed_row.loan_id is distinct from new.loan_id
       or reversed_row.credit_card_id is distinct from new.credit_card_id
       or reversed_row.adjustment_type = 'reversal'
       or reversed_row.status <> 'posted'
       or reversed_row.amount <> new.amount then
      raise exception 'Invalid adjustment reversal';
    end if;

    if exists (
      select 1
      from public.debt_adjustments
      where reverses_adjustment_id = new.reverses_adjustment_id
        and status = 'posted'
        and id is distinct from new.id
    ) then
      raise exception 'Adjustment has already been reversed';
    end if;
  end if;

  return new;
end;
$$;

create or replace function public.validate_payment_allocation()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  payment_row public.debt_payments%rowtype;
  adjustment_row public.debt_adjustments%rowtype;
  allocated_total numeric(14,2);
begin
  perform pg_advisory_xact_lock(
    hashtextextended('ppb-payment-allocation:' || new.payment_id::text, 0)
  );

  select * into payment_row
  from public.debt_payments
  where id = new.payment_id;

  if payment_row.id is null
     or payment_row.user_id <> new.user_id
     or payment_row.status <> 'posted' then
    raise exception 'Payment does not belong to the user';
  end if;

  if new.adjustment_id is not null then
    perform pg_advisory_xact_lock(
      hashtextextended('ppb-adjustment-allocation:' || new.adjustment_id::text, 0)
    );

    select * into adjustment_row
    from public.debt_adjustments
    where id = new.adjustment_id;

    if adjustment_row.id is null
       or adjustment_row.user_id <> new.user_id
       or adjustment_row.debt_type <> payment_row.debt_type
       or adjustment_row.loan_id is distinct from payment_row.loan_id
       or adjustment_row.credit_card_id is distinct from payment_row.credit_card_id
       or adjustment_row.status <> 'posted'
       or adjustment_row.adjustment_type in ('credit', 'reversal') then
      raise exception 'Adjustment does not belong to the payment debt';
    end if;

    if new.component = 'principal'
       or (adjustment_row.adjustment_type = 'finance_charge' and new.component <> 'finance_charge')
       or (adjustment_row.adjustment_type = 'additional_interest' and new.component <> 'interest')
       or (adjustment_row.adjustment_type = 'late_fee' and new.component <> 'penalty')
       or (adjustment_row.adjustment_type in (
             'over_limit_fee', 'annual_fee', 'collection_fee',
             'restructuring_fee', 'other_charge'
           ) and new.component not in ('fee', 'other')) then
      raise exception 'Allocation component does not match the adjustment type';
    end if;

    select coalesce(sum(amount), 0)
      into allocated_total
    from public.payment_allocations
    where adjustment_id = new.adjustment_id
      and id is distinct from new.id;

    if allocated_total + new.amount > adjustment_row.amount then
      raise exception 'Allocations cannot exceed the adjustment amount';
    end if;
  elsif new.component not in ('principal', 'interest', 'other') then
    raise exception 'Charge, penalty, and fee allocations require an adjustment';
  end if;

  select coalesce(sum(amount), 0)
    into allocated_total
  from public.payment_allocations
  where payment_id = new.payment_id
    and id is distinct from new.id;

  if allocated_total + new.amount > payment_row.amount then
    raise exception 'Allocations cannot exceed the payment amount';
  end if;

  return new;
end;
$$;

create trigger debt_adjustments_validate
before insert or update on public.debt_adjustments
for each row execute function public.validate_debt_accounting_row();

create trigger debt_payments_validate
before insert or update on public.debt_payments
for each row execute function public.validate_debt_accounting_row();

create trigger payment_allocations_validate
before insert or update on public.payment_allocations
for each row execute function public.validate_payment_allocation();

create trigger debt_adjustments_set_updated_at
before update on public.debt_adjustments
for each row execute function public.set_updated_at();

create trigger debt_payments_set_updated_at
before update on public.debt_payments
for each row execute function public.set_updated_at();

create or replace function public.record_debt_adjustment(
  p_user_id uuid,
  p_debt_type text,
  p_debt_id bigint,
  p_adjustment_type text,
  p_amount numeric,
  p_effective_date date,
  p_due_date date,
  p_description text,
  p_transaction_id bigint,
  p_transaction_category text,
  p_transaction_note text,
  p_reverses_adjustment_id bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_previous_balance numeric(14,2);
  v_current_balance numeric(14,2);
  balance_delta numeric(14,2);
  adjustment_id bigint;
begin
  if (select auth.uid()) is distinct from p_user_id
     and coalesce((select auth.role()), '') <> 'service_role' then
    raise exception 'Not authorized';
  end if;
  if p_amount is null or p_amount <= 0 then raise exception 'Adjustment amount must be positive'; end if;
  if (p_adjustment_type = 'reversal') <> (p_reverses_adjustment_id is not null) then
    raise exception 'A reversal must identify exactly one adjustment';
  end if;
  balance_delta := case when p_adjustment_type in ('credit', 'reversal') then -p_amount else p_amount end;

  if p_debt_type = 'loan' then
    select l.balance into v_previous_balance from public.loans l
      where id = p_debt_id and user_id = p_user_id for update;
    if v_previous_balance is null then raise exception 'Loan not found'; end if;
    v_current_balance := round(v_previous_balance + balance_delta, 2);
    if v_current_balance < 0 then raise exception 'Adjustment exceeds the debt balance'; end if;
    update public.loans set balance = v_current_balance where id = p_debt_id;
  elsif p_debt_type = 'credit_card' then
    select c.current_balance into v_previous_balance from public.credit_cards c
      where id = p_debt_id and user_id = p_user_id for update;
    if v_previous_balance is null then raise exception 'Credit card not found'; end if;
    v_current_balance := round(v_previous_balance + balance_delta, 2);
    if v_current_balance < 0 then raise exception 'Adjustment exceeds the debt balance'; end if;
    update public.credit_cards
      set current_balance = v_current_balance,
          statement_balance = greatest(0, round(statement_balance + balance_delta, 2))
      where id = p_debt_id;
  else
    raise exception 'Invalid debt type';
  end if;

  insert into public.transactions(id, user_id, kind, amount, category, note, date)
  values (
    p_transaction_id, p_user_id,
    case when balance_delta < 0 then 'income' else 'expense' end,
    p_amount, p_transaction_category, p_transaction_note, p_effective_date
  );

  insert into public.debt_adjustments(
    user_id, debt_type, loan_id, credit_card_id, adjustment_type, amount,
    effective_date, due_date, description, source_transaction_id, reverses_adjustment_id
  ) values (
    p_user_id, p_debt_type,
    case when p_debt_type = 'loan' then p_debt_id end,
    case when p_debt_type = 'credit_card' then p_debt_id end,
    p_adjustment_type, p_amount, p_effective_date, p_due_date,
    coalesce(p_description, ''), p_transaction_id, p_reverses_adjustment_id
  ) returning id into adjustment_id;

  return jsonb_build_object(
    'transaction_id', p_transaction_id, 'adjustment_id', adjustment_id,
    'previous_balance', v_previous_balance, 'current_balance', v_current_balance
  );
end;
$$;

create or replace function public.record_debt_payment(
  p_user_id uuid,
  p_debt_type text,
  p_debt_id bigint,
  p_amount numeric,
  p_payment_date date,
  p_due_date date,
  p_source_account_key text,
  p_transaction_id bigint,
  p_transaction_category text,
  p_transaction_note text,
  p_advanced_due_date date default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_previous_balance numeric(14,2);
  v_current_balance numeric(14,2);
  payment_id bigint;
  principal_amount numeric(14,2);
  remaining_amount numeric(14,2);
  outstanding_charges numeric(14,2);
  available_adjustment numeric(14,2);
  allocation_amount numeric(14,2);
  component_name text;
  adjustment_row record;
begin
  if (select auth.uid()) is distinct from p_user_id
     and coalesce((select auth.role()), '') <> 'service_role' then
    raise exception 'Not authorized';
  end if;
  if p_amount is null or p_amount <= 0 then raise exception 'Payment amount must be positive'; end if;

  if p_debt_type = 'loan' then
    select l.balance into v_previous_balance from public.loans l
      where id = p_debt_id and user_id = p_user_id for update;
  elsif p_debt_type = 'credit_card' then
    select c.current_balance into v_previous_balance from public.credit_cards c
      where id = p_debt_id and user_id = p_user_id for update;
  else
    raise exception 'Invalid debt type';
  end if;
  if v_previous_balance is null then raise exception 'Debt not found'; end if;
  if p_amount > v_previous_balance then raise exception 'Payment exceeds the debt balance'; end if;

  select greatest(0, coalesce(sum(
    case when a.signed_amount > 0
      then greatest(0, a.signed_amount - coalesce(x.allocated, 0))
      else a.signed_amount end
  ), 0)) into outstanding_charges
  from public.debt_adjustments a
  left join lateral (
    select sum(pa.amount) allocated from public.payment_allocations pa where pa.adjustment_id = a.id
  ) x on true
  where a.user_id = p_user_id and a.debt_type = p_debt_type and a.status = 'posted'
    and ((p_debt_type = 'loan' and a.loan_id = p_debt_id)
      or (p_debt_type = 'credit_card' and a.credit_card_id = p_debt_id));

  principal_amount := least(p_amount, greatest(0, v_previous_balance - outstanding_charges));
  remaining_amount := round(p_amount - principal_amount, 2);
  v_current_balance := round(v_previous_balance - p_amount, 2);

  insert into public.transactions(id, user_id, kind, amount, category, note, date)
  values (p_transaction_id, p_user_id, 'expense', p_amount, p_transaction_category, p_transaction_note, p_payment_date);

  insert into public.debt_payments(
    user_id, debt_type, loan_id, credit_card_id, amount, payment_date,
    source_account_key, source_transaction_id, legacy_due_key
  ) values (
    p_user_id, p_debt_type,
    case when p_debt_type = 'loan' then p_debt_id end,
    case when p_debt_type = 'credit_card' then p_debt_id end,
    p_amount, p_payment_date, p_source_account_key, p_transaction_id,
    p_debt_type || ':' || p_debt_id || ':' || p_due_date
  ) returning id into payment_id;

  if principal_amount > 0 then
    insert into public.payment_allocations(user_id, payment_id, component, amount)
    values (p_user_id, payment_id, 'principal', principal_amount);
  end if;

  for adjustment_row in
    select a.*, coalesce(x.allocated, 0) allocated
    from public.debt_adjustments a
    left join lateral (
      select sum(pa.amount) allocated from public.payment_allocations pa where pa.adjustment_id = a.id
    ) x on true
    where remaining_amount > 0 and a.user_id = p_user_id
      and a.debt_type = p_debt_type and a.status = 'posted'
      and a.adjustment_type not in ('credit', 'reversal')
      and ((p_debt_type = 'loan' and a.loan_id = p_debt_id)
        or (p_debt_type = 'credit_card' and a.credit_card_id = p_debt_id))
    order by a.due_date, a.effective_date, a.id
    for update of a
  loop
    available_adjustment := greatest(0, adjustment_row.amount - adjustment_row.allocated);
    allocation_amount := least(remaining_amount, available_adjustment);
    if allocation_amount <= 0 then continue; end if;
    component_name := case adjustment_row.adjustment_type
      when 'finance_charge' then 'finance_charge'
      when 'additional_interest' then 'interest'
      when 'late_fee' then 'penalty'
      when 'other_charge' then 'other'
      else 'fee' end;
    insert into public.payment_allocations(user_id, payment_id, adjustment_id, component, amount)
    values (p_user_id, payment_id, adjustment_row.id, component_name, allocation_amount);
    remaining_amount := round(remaining_amount - allocation_amount, 2);
  end loop;

  if remaining_amount <> 0 then raise exception 'Payment allocation could not be reconciled'; end if;

  if p_debt_type = 'loan' then
    update public.loans set balance = v_current_balance,
      due = coalesce(p_advanced_due_date, due) where id = p_debt_id;
  else
    update public.credit_cards set current_balance = v_current_balance,
      statement_balance = greatest(0, round(statement_balance - p_amount, 2))
      where id = p_debt_id;
  end if;

  return jsonb_build_object(
    'transaction_id', p_transaction_id, 'payment_id', payment_id,
    'previous_balance', v_previous_balance, 'current_balance', v_current_balance
  );
end;
$$;

create index debt_adjustments_user_date_idx
  on public.debt_adjustments(user_id, effective_date desc);

create index debt_adjustments_loan_idx
  on public.debt_adjustments(loan_id)
  where loan_id is not null;

create index debt_adjustments_credit_card_idx
  on public.debt_adjustments(credit_card_id)
  where credit_card_id is not null;

create unique index debt_adjustments_source_transaction_unique
  on public.debt_adjustments(user_id, source_transaction_id)
  where source_transaction_id is not null and status = 'posted';

create unique index debt_adjustments_single_posted_reversal
  on public.debt_adjustments(reverses_adjustment_id)
  where reverses_adjustment_id is not null and status = 'posted';

create index debt_payments_user_date_idx
  on public.debt_payments(user_id, payment_date desc);

create index debt_payments_loan_idx
  on public.debt_payments(loan_id)
  where loan_id is not null;

create index debt_payments_credit_card_idx
  on public.debt_payments(credit_card_id)
  where credit_card_id is not null;

create unique index debt_payments_source_transaction_unique
  on public.debt_payments(user_id, source_transaction_id)
  where source_transaction_id is not null and status = 'posted';

create index payment_allocations_payment_idx
  on public.payment_allocations(payment_id);

create index payment_allocations_adjustment_idx
  on public.payment_allocations(adjustment_id)
  where adjustment_id is not null;

create unique index payment_allocations_component_unique
  on public.payment_allocations(payment_id, component, coalesce(adjustment_id, 0));

alter table public.debt_adjustments enable row level security;
alter table public.debt_payments enable row level security;
alter table public.payment_allocations enable row level security;

create policy debt_adjustments_own_rows
on public.debt_adjustments
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy debt_payments_own_rows
on public.debt_payments
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy payment_allocations_own_rows
on public.payment_allocations
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

revoke all on table public.debt_adjustments from anon;
revoke all on table public.debt_payments from anon;
revoke all on table public.payment_allocations from anon;

-- Accounting rows are append-only for app users. Corrections are represented by
-- a reversal row; only trusted backend maintenance may void a posted row.
grant select, insert on table public.debt_adjustments to authenticated;
grant select, insert on table public.debt_payments to authenticated;
grant select, insert on table public.payment_allocations to authenticated;

grant all on table public.debt_adjustments to service_role;
grant all on table public.debt_payments to service_role;
grant all on table public.payment_allocations to service_role;

grant usage, select on sequence public.debt_adjustments_id_seq to authenticated, service_role;
grant usage, select on sequence public.debt_payments_id_seq to authenticated, service_role;
grant usage, select on sequence public.payment_allocations_id_seq to authenticated, service_role;

revoke all on function public.set_updated_at() from public, anon, authenticated;
revoke all on function public.validate_debt_accounting_row() from public, anon, authenticated;
revoke all on function public.validate_payment_allocation() from public, anon, authenticated;
revoke all on function public.record_debt_adjustment(uuid,text,bigint,text,numeric,date,date,text,bigint,text,text,bigint) from public, anon;
revoke all on function public.record_debt_payment(uuid,text,bigint,numeric,date,date,text,bigint,text,text,date) from public, anon;
grant execute on function public.set_updated_at() to service_role;
grant execute on function public.validate_debt_accounting_row() to service_role;
grant execute on function public.validate_payment_allocation() to service_role;
grant execute on function public.record_debt_adjustment(uuid,text,bigint,text,numeric,date,date,text,bigint,text,text,bigint) to authenticated, service_role;
grant execute on function public.record_debt_payment(uuid,text,bigint,numeric,date,date,text,bigint,text,text,date) to authenticated, service_role;

comment on table public.debt_adjustments is
  'Structured finance charges, penalties, fees, credits, and reversals. Existing PPB transaction markers remain supported during migration.';

comment on table public.debt_payments is
  'Structured loan and credit-card payments. source_transaction_id prevents the same payment from being counted twice.';

comment on table public.payment_allocations is
  'Breakdown of each payment across principal, interest, charges, penalties, and fees.';

commit;
